refactor: is-full-machine

diff --git a/packages/jehon/usr/bin/jh-is-full-machine b/packages/jehon/usr/bin/jh-is-full-machine
--- a/packages/jehon/usr/bin/jh-is-full-machine
+++ b/packages/jehon/usr/bin/jh-is-full-machine
@@ -12,6 +12,21 @@ if [ "$1" == "-v" ]; then
     ECHO="echo"
 fi
 
+if ! type systemctl &>/dev/null; then
+    $ECHO "Ko, systemctl not found"
+    exit 1
+fi
+
+if [ "$(systemctl is-system-running)" == "offline" ]; then
+    $ECHO "Ko, systemd is in offline state"
+    exit 1
+fi
+
+if [ "$(systemctl is-system-running)" == "unknown" ]; then
+    $ECHO "Ko, systemd is in unknown state"
+    exit 1
+fi
+
 if [ "$PID1" != 'systemd' ]; then
     $ECHO "Ko, systemd is not pid 1"
     exit 1
